run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: true
  skip-dirs:
    - scripts
    - vendor
    - .circleci
    - .github
    - .vscode
  skip-files:
    - "./...*_test.go"
  skip-dirs-use-default: false
  modules-download-mode: mod
  allow-parallel-runners: true
severity:
  default-severity: error
  case-sensitive: true
linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
  disable:
    - gofumpt
    - gomnd
    - nolintlint
    - depguard
    - wrapcheck
    - exhaustruct
