version: "3.9"
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=pismo_challenge
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=development
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  server:
    build: .
    environment:
      - DATABASE_URL=postgresql://dev:development@postgres/pismo_challenge?sslmode=disable
    ports:
      - 3000:3000
    depends_on:
      - postgres
volumes:
  pgdata: {}
