name: Go

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: development
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          cache-dependency-path: go.sum
      - name: Install deps
        run: make install
      - name: Run linter
        run: make lint
      - name: Run tests
        run: go test -json ./... > test_result.json
        env:
          DATABASE_URL: 'postgresql://dev:development@localhost/postgres?sslmode=disable'
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: go-results
          path: test_result.json
