name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          cache-dependency-path: go.sum
      - name: Install deps
        run: make install
      - name: Run linter
        run: make lint
      - name: Run tests
        run: go test ./... -json > test_result.json
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: go-results
          path: test_result.json
